config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root'home#index'
  
  resources :promotions do
    post 'generate_coupons', on: :member
  end

  resources :product_categories


  resources :coupons, only: [] do
    post 'inactivate', on: :member
    post 'active', on: :member
    get 'search', on: :collection
  end

  namespace 'api' do
    namespace 'v1' do
      resources :coupons, param: :code, only: %i[show] do
        post 'burn', on: :member
      end
      #get 'coupons/:code', to: 'coupons#show'
      #post 'coupons/:code/burn', to: 'coupons#burn'
      end 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion, dependent: :destroy
  scope :search, ->(query) { where('code equal ?', "%#{query}%") }
  enum status: { active: 0, inactivate: 10, burn: 20 }
  validates :order, presence: true, on: :coupon_burn

  def title
    "#{code} (#{Coupon.human_attribute_name("status.#{status}")})"
  end

  def as_json(options = {})
    super({ methods: %i[discount_rate expiration_date],
            only: %i[] }.merge(options))
  end

  def burn!(order)
    self.order = order
    self.status = :burn
    save!(context: :coupon_burn)
    # raise ActiveRecord::RecordInvalid unless order.present?
    # update!(order: order, status: :burn)
    # save! levanta o mesmo erro do RecordInvalid, entao o rescue continua funcionando no controller.
  end

  delegate :discount_rate, to: :promotion

  def expiration_date
    I18n.l(promotion.expiration_date)
  end

  def expired?
    promotion.expiration_date < Date.current
  end

  def category_is_valid?(category)
    if promotion.product_categories.count.zero? || (category.nill? && promotion.product_categories.find_by(code: category))
      return true
    end

    false
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :product_category_promotions, dependent: :destroy
  has_many :promotions
  validates :name, :code, presence: true
  validates :name, :code, uniqueness: true
  scope :search, ->(query) { where('name like ? OR code like ?', "%#{query}%", "%#{query}%") }
end

app/models/product_category_promotion.rb
class ProductCategoryPromotion < ApplicationRecord
  belongs_to :product_category
  belongs_to :promotion
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :coupons, dependent: :destroy
  has_many :product_category_promotions, dependent: :destroy
  has_many :product_categories, through: :product_category_promotions, dependent: :destroy
  # pural de product_categories, pq sao varias; e passa a tabela (plural) pra unir - join table)

  validates :name, :code, :discount_rate, :coupon_quantity, :expiration_date,
            presence: true
  validates :code, uniqueness: true
  validates :coupon_quantity, numericality: { greater_than: 0, message: 'Deve ser maior que 0' }

  scope :search, lambda { |query|
                   where('name like ? OR description like ? OR code like ?',
                         "%#{query}%", "%#{query}%", "%#{query}%")
                 }

  def generate_coupons!
    raise 'Cupons já foram gerados' if coupons.any?

    codes =
      (1..coupon_quantity).map do |number|
        { code: "#{code}-#{'%04d' % number}" }
      end
    coupons
      .create_with(created_at: Time.zone.now, updated_at: Time.zone.now)
      .insert_all!(codes)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validate :email_domain

  def email_domain
    return if email.include?('@locaweb.com.br')

    errors.add(:email, 'domínio inválido')
  end
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::API
    end
  end
end

app/controllers/api/v1/coupons_controller.rb
module Api
  module V1
    class CouponsController < ApiController
      before_action :set_coupon
      before_action :verify_order_code

      def show
        if @coupon.expired?
          render json: 'Cupom fora do prazo da promoção', status: :precondition_failed
        else
          render json: @coupon, status: :ok
        end
      end

      def burn
        unless @coupon.category_is_valid? params[:category]
          return render json: 'Categoria não encontrada. Ação não pode ser realizada',
                        status: :unauthorized
        end

        @coupon.burn!(params.dig(:order, :code))
        render json: 'Cupom utilizado com sucesso', status: :ok
      rescue ActiveRecord::RecordInvalid
        render json: '', status: :unprocessable_entity
      end

      private

      def set_coupon
        @coupon = Coupon.find_by!(code: params[:code])
      rescue ActiveRecord::RecordNotFound
        render json: 'Cupom não encontrado.', status: :not_found
      end

      def verify_order_code
        return if params.fetch(:order, :code).present?

        render json: '', status: :precondition_failed
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def search
    @coupon = Coupon.find_by(code: params[:search]) if params[:search]
  end

  def inactivate
    @coupon = Coupon.find(params[:id])
    @coupon.inactivate!
    flash[:success] = t('.sucess')
    redirect_to @coupon.promotion
  end

  def active
    @coupon = Coupon.find(params[:id])
    @coupon.active!
    flash[:success] = t('.sucess')
    redirect_to @coupon.promotion
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_categories, only: %i[show destroy edit update]
  before_action :authenticate_user!

  def index
    @product_categories = if params[:search]
                            ProductCategory.search(params[:search])
                          else
                            ProductCategory.all
                          end
  end

  def new
    @product_categories = ProductCategory.new
  end

  def show; end

  def edit; end

  def update
    if @product_categories.update(product_categories_params)
      redirect_to product_categories_path
    else
      render :edit
    end
  end

  def destroy
    @product_categories.destroy
    redirect_to product_categories_path
  end

  def create
    @product_categories = ProductCategory.new(product_categories_params)
    if @product_categories.save
      redirect_to @product_categories
    else
      render :new
    end
  end

  private

  def set_product_categories
    @product_categories = ProductCategory.find(params[:id])
  end

  def product_categories_params
    params
      .require(:product_category)
      .permit(:name, :code, :status)
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promotion, only: %i[show edit update destroy generate_coupons]

  def index
    @promotions = if params[:search]
                    Promotion.search(params[:search])
                  else
                    Promotion.all
                  end
  end

  def show; end

  def edit; end

  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    if @promotion.save
      redirect_to @promotion
    else
      render :new
    end
  end

  def update
    if @promotion.update(promotion_params)
      redirect_to @promotion
    else
      render :edit
    end
  end

  def destroy
    @promotion.destroy
    redirect_to promotions_path
  end

  def generate_coupons
    @promotion.generate_coupons!
    flash[:success] = 'Cupons gerados com sucesso'
    redirect_to @promotion
  end

  private

  def set_promotion
    @promotion = Promotion.find(params[:id])
  end

  def promotion_params
    params
      .require(:promotion)
      .permit(:name, :description, :code, :discount_rate,
              :expiration_date, :coupon_quantity,
              product_category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coupons/_coupon.html.erb
<table class="table table-hover">
  <tr>  
  <% Coupon.human_attribute_name(:code) %>
    <td><%= coupon.title %></td>
    <% if coupon.active? %>
    <td><%= link_to t('.inactivate'), inactivate_coupon_path(coupon), method: :post %></td>
    <% else %>
    <td><%= link_to t('.active'), active_coupon_path(coupon), method: :post %></td>
    <% end %>
  </tr>
</table>

app/views/coupons/search.html.erb
<% if @coupon.nil? %>
    <p>Nenhum cupom encontrado</p>
<% else %>
    <strong>Cupom encontrado para promoção: 
    <%= link_to "#{@coupon.promotion.name}", promotion_path(@coupon.promotion) %></strong>
    <br>
    <%= render @coupon %>
    <br>
    <strong>Detalhes de cupom </strong>
    <dd>Nome da promoção: <%= @coupon.promotion.name %> </dd>
    <dd>Desconto: <%= @coupon.promotion.discount_rate %>% </dd>
    <dd>Data de término: <%= @coupon.expiration_date %> </dd>
    <br>
     <%= link_to promotions_path do %>
        <i class="fa fa-angle-double-left"></i> Voltar
      <% end %>
<% end %>

app/views/home/index.html.erb
<hr>
<strong>
  <center><h1 style ="color:Navy;"> Promotion System  </h1> 
</strong>
<p style="color:SteelBlue">Boas vindas ao sistema de gestão de promoções </p>
<hr>
<% if !user_signed_in? %>
<%= link_to 'Login', new_user_session_path %>
<p style="color:Navy;"> Faça login ou registre-se para acessar as funcionalidades </p>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>PromotionSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header" role="banner">
    <div id="navbar_links">
    <div class="container"> 
      <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
        <class="active">
        <a style ="color:white;" href="/">Página Inicial <i class="fa fa-home"></i> </a>| 
        <a style ="color:white;" href="/promotions">Promoções</a> | 
        <a style ="color:white;" href="/product_categories">Categorias</a> 
      </nav>
    </div></div>
    </header>

<div class="container">
  <class="notice"><%= notice %>
  <class="alert"><%= flash[:alert] %>
  <% if flash[:success] %>
    <%= flash[:success] %>
  <% end %>
</div>

<%= yield %>

  <% if user_signed_in? %>
    <div id = 'body_links'>
    <center><strong><%= link_to 'Promoções', promotions_path %></strong> |
    <strong><%= link_to 'Categorias de produtos', product_categories_path %></strong>
    <hr>
    </div>
    <center>
    <i class="fa fa-user-circle"></i> <strong><%= current_user.email %></strong> <br>
    <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    </center>
  <% end %>

  <footer>
  <footer class="footer">
  <hr>
    <div class="container footer-info">
    <center style="color:CadetBlue;"> QUERO SER DEV - GIRLS <%= Time.now.year %></center>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

app/views/product_categories/_form.html.erb
<%= render 'shared/errors', object: @product_categories %>

<div class="input-group input-group-lg">
    <%= form_with model: @product_categories, local: true do |f| %>
    <ul><%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: "form-control" %></ul>
    <ul><%= f.label :code, 'Código' %>
    <%= f.text_field :code , class: "form-control" %></ul>
    <br>
    <ul><%= f.submit 'Salvar categoria', class: 'btn btn-info'  %></ul>
</div>

<% end %>

app/views/product_categories/edit.html.erb
<% if user_signed_in? %>
<center>
  <hr><strong><p style ="color:CadetBlue;"> Editar categoria de produto  </p></strong><hr>
</center>
  <%= render 'form', product_categories: @product_categories %><br>
  
  <center>
  <%= link_to product_categories_path do %>
    <i class="fa fa-angle-double-left"></i> Voltar | 
  <% end %>

  <%= link_to root_path do %>
    <i class="fa fa-home"></i> Home
  <% end %>
  </center>


<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/product_categories/index.html.erb
<% if user_signed_in? %>
    <hr><strong><center><h2 style ="color:CadetBlue;"> Categoria de produto  </h2></strong><br>
    <%= link_to 'Registrar uma categoria', new_product_category_path, class: "btn btn-primary" %> 
        <br>
        <br>
        <% if !@product_categories.empty? %>
            <div id='categories'>
                <%= form_tag(product_categories_path, method: :get) do %>
                    <%= text_field_tag 'search', nil, placeholder: 'Buscar categoria' %> |
                    <%= submit_tag 'Pesquisar',class: 'btn btn-white'  %>
                <% end %> </center> <hr>
            </div><br>

        <table class="table">
            <th><h5 style ="color:DarkSlateGray;">Nome</h5></th>
            <th><h5 style ="color:DarkSlateGray;">Código</h5></th>
        </table>
        
        <table class="table">
            <% @product_categories.each do |product_category| %>
                <td> <%= link_to product_category.name, product_category %> </td>
                <td> <%= product_category.code %> </td>
        </table>
            <% end %>
        <% else %>
            <br>
            <center><p>Nenhuma categoria cadastrada </p></center>
        <% end %>
  <%= link_to root_path do %>
    <i class="fa fa-angle-double-left"></i> Voltar
  <% end %>
<% else %>
    <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/product_categories/new.html.erb
<% if user_signed_in? %>
  <center><hr><strong><h4 style ="color:CadetBlue;"> Registrar nova categoria </h4></strong><hr></center>
  <hr>
  <%= render 'form', product_categories: @product_categories %> <br>
   <center>
  <%= link_to product_categories_path do %>
    <i class="fa fa-angle-double-left"></i> Voltar | 
  <% end %>

  <%= link_to root_path do %>
    <i class="fa fa-home"></i> Home
  <% end %>
  </center>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/product_categories/show.html.erb
<% if user_signed_in? %>
  <hr><strong><p style ="color:CadetBlue;"> Categoria de produto </p></strong>
  <hr>
  <h1> <%= @product_categories.name %> </h1>
  <p> <%= @product_categories.code %> </p>
  <hr>
  <%= link_to product_categories_path do %>
    <i class="fa fa-angle-double-left"></i> Voltar | 
  <% end %>
  <%= link_to 'Editar', edit_product_category_path(@product_categories), class: "btn btn-primary" %>
  <%= link_to 'Deletar', @promotion, method: :delete, data: {confirm: 'Confirmar ação?'}, class: "btn btn-danger"%>

<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/promotions/_form.html.erb
<%= render 'shared/errors', object: @promotion %>
  
  <%= form_with model: @promotion do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>
  <%= f.label :code, 'Código' %>
  <%= f.text_field :code, class: "form-control" %>
  <%= f.label :discount_rate %>
  <%= f.number_field :discount_rate, class: "form-control" %>
  <%= f.label :coupon_quantity %>
  <%= f.number_field :coupon_quantity, class: "form-control" %>
  <%= f.label :expiration_date, 'Data de término' %>
  <%= f.date_field :expiration_date, class: "form-control" %>
  <br>
  <hr>
  <p> <strong> Selecione se categorias associadas a esta promoção </p></strong>
  <%= f.label :product_category_ids, 'Válidas:' %>
  <br>
  <%= f.collection_check_boxes :product_category_ids, ProductCategory.all, :id, :name, class: "form-control"%>
  <br>
  <hr>
  <%= f.submit 'Salvar', class:"btn btn-primary"  %>

<% end %>

app/views/promotions/edit.html.erb
<% if user_signed_in? %>
  <hr><strong><p style ="color:CadetBlue;"> Editar promoção </p></strong><hr>
  <%= render 'form', promotions: @promotions %><br>
   <center>
  <%= link_to promotions_path do %>
    <i class="fa fa-angle-double-left"></i> Voltar | 
  <% end %>
  <%= link_to root_path do %>
    <i class="fa fa-home"></i> Home
  <% end %>
  </center>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/promotions/index.html.erb
<% if user_signed_in? %>
    <hr><strong><center><h2 style ="color:CadetBlue;"> Promoções </h2> <br>
      <%= link_to "Registrar uma promoção", new_promotion_path, :method => "get", class: "btn btn-primary" %></strong> <br>
      <br>
      <% if !@promotions.empty? %>
        <div id= 'promotion'>
          <%= form_tag(promotions_path, method: :get) do %>
              <%= text_field_tag 'search','', placeholder: 'Promoção' %> |
              <%= submit_tag 'Pesquisar', class: 'btn btn-white' %>
          <% end %></div><br>
        <div id= 'coupons'>
        <%= form_tag(search_coupons_path, method: :get) do %>
            <%= text_field_tag 'search', '', placeholder: 'Código de cupom' %> |
            <%= submit_tag 'Pesquisar', class: 'btn btn-white' %>
        <% end %></div> </center><hr>
        
        <table class="table">
        <th><h5 style ="color:DarkSlateGray;">Nome</h5></th>
        <th><h5 style ="color:DarkSlateGray;">Descrição</h5></th>
        <th><h5 style ="color:DarkSlateGray;">Desconto</h5></th>
        </table>
        
        <table class="table">
        <% @promotions.each do |promotion| %>
          <td><strong> <%= link_to promotion.name, promotion %></strong></td>
          <td><%= promotion.description %></td>
          <td><%= number_to_percentage promotion.discount_rate, precision: 2, separator: ',' %></td>
        </table>
        <% end %>
      <% else %>
      <center><p>Nenhuma promoção cadastrada </p></center>
      <% end %>
      <%= link_to root_path do %>
        <i class="fa fa-angle-double-left"></i> Voltar
      <% end %>
  <% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/promotions/new.html.erb
<% if user_signed_in? %>
  <center><hr><strong><h4 style ="color:CadetBlue;"> Registrar nova promoção  </h4></strong><hr></center>
  <%= render 'form', promotions: @promotions %><br>
  <center>
  <%= link_to promotions_path do %>
    <i class="fa fa-angle-double-left"></i> Voltar | 
  <% end %>
  <%= link_to root_path do %>
    <i class="fa fa-home"></i> Home
  <% end %>
  </center>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/promotions/show.html.erb
<% if user_signed_in? %>
      <hr><strong><h2 style ="color:CadetBlue;"> <%= @promotion.name %></h2></strong><hr>
      <i><strong><h3> <%= @promotion.description %> </h3></strong></i>
      <dl>
        <dt> Desconto em porcentagem </dt>
        <dd> <%= number_to_percentage @promotion.discount_rate, precision: 2, separator: ',' %> </dd>
        <dt> Código </dt>
        <dd> <%= @promotion.code %> </dd>
        <dt> Data de término </dt>
        <dd> <%= @promotion.expiration_date.strftime('%d/%m/%Y') %> </dd>
        <dt> Número de cupons </dt>
        <dd> <%= @promotion.coupon_quantity %> </dd>
      </dl>
      <%= link_to promotions_path do %>
          <i class="fa fa-angle-double-left"></i> Voltar | 
      <% end %>
      <%= link_to 'Editar', edit_promotion_path(@promotion), class: "btn btn-primary" %> 
      <%= link_to 'Deletar', @promotion, method: :delete, data: {confirm: 'Confirmar ação?'}, class: "btn btn-danger" %>
      <hr>
      <strong>Categorias válidas <strong>

        <% if @promotion.product_categories.empty? %>
          <p> Nenhuma categoria cadastrada </p>
        <% else %>
          <% @promotion.product_categories.each do |product_category| %>
            <p><%= product_category.name %></p>
            <p><%= product_category.code %></p>
          <% end %>
        <% end %><hr>
    
    <% if @promotion.coupons.empty? %>
      <%= link_to 'Emitir Cupons', generate_coupons_promotion_path, method: :post, class: "btn btn-primary" %>
    <% else %>
      <h3 style ="color:CadetBlue;"> Cupons </h3>
      <%= render @promotion.coupons %>
    <% end %>
      
<% else %>
<%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id = "error_explanation">
    <div class = "alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>